version: '2'
services:
  biojs-builder:
    command: /bin/sh -c "npm i && npm run make && npm run startDev"
    image: node:10
    working_dir: /opt
    volumes:
      - .:/opt
    environment:
      TERM: dumb
    ports:
      - 3000:3000
    networks:
      - service

networks:
  service:
